# name: anamesia_implementation
# description: "A new Flutter project."
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: ^3.8.1

# dependencies:
#   flutter:
#     sdk: flutter

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# flutter:
#   uses-material-design: true
name: ai_anamnesis_app
description: AI-powered anamnesis documentation app using Flutter and OpenAI GPT-4.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # CSV export functionality
  csv: ^5.0.2
  
  # File system access
  path_provider: ^2.1.1
  
  # Sharing functionality
  share_plus: ^7.2.1
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
    - assets/data/ # This line is crucial for including your JSON